language: javascript
branches:
  only:
  - master
install:
- sudo apt-get install -y yarn
- yarn install
script:
- yarn build
deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
