language: node_js
node_js:
  - "node"
branches:
  only:
  - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn build
  - cp CNAME ./dist/CNAME # copy CNAME file to root of dist so we go to the subdomain
  - ls ./dist
deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
cache:
    yarn: true
    directories:
        - "node_modules"
